git:
  quiet: true
# branches:
#   only:
#     - master
language: node_js
node_js:
  - "10"
dist: trusty
services:
  -postgresql
cache:
  directories:
  - node_modules
install:
  - npm install
before_script:
  - psql -c 'create database "BR-test-db";' -U postgres
env:
  global:
    - TESTPW=''
script:
  - nohup npm run start &
  - knex migrate:latest
  - knex seed:run
  - sleep 3
  - npm run test #when we add test uncomment
notifications:
  email:
    on_failure: change
  # slack: #If we want notifications on slack
  #   rooms:
  #     - <account>:<token>#labs11_uber-travis-builds
  #   on_failure: change
  #   on_pull_requests: false